# Tell Spring Boot where your local PostgreSQL lives
spring.datasource.url=jdbc:postgresql://localhost:5432/myblog_db
spring.datasource.username=ayazizi
spring.datasource.password=${DB_PASSWORD:}

# Allow Hibernate to automatically map your Java classes into relational tables (ddl: risky in production!!!)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
