# Tell Spring Boot where your local PostgreSQL lives
spring.datasource.url=jdbc:postgresql://localhost:5432/myblog_db
spring.datasource.username=ayazizi
spring.datasource.password=${DB_PASSWORD:}

# Allow Hibernate to automatically map your Java classes into relational tables (`ddl-auto= update` is risky in production!!!) -> we are using flyway for migrations instead.
spring.jpa.hibernate.ddl-auto=validate 
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.flyway.enabled=true
hibernate.default_schema=public
hibernate.default_catalog=myblog_db